[build-system]
requires = ["numpy", "setuptools>=61", "setuptools-scm[simple]>=8", "torch", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "forward_warp"
description = "An optical flow forward warp's lib with backpropagation using pytorch."
dynamic = ["version"]
license = "MIT"
dependencies = [
    "torch",
]

[tool.setuptools]
packages = ["forward_warp"]

[tool.setuptools_scm]
version_file = "forward_warp/_version.py"

[tool.ruff]
line-length = 88
extend-exclude = ["forward_warp/_version.py"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[project.urls]
Repository = "https://github.com/samaust/Forward-Warp"
